/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevendedoresRouteImport } from './routes/revendedores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRemoteConfigRouteImport } from './routes/api/public/remote-config'

const RevendedoresRoute = RevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemoteConfigRoute = ApiPublicRemoteConfigRouteImport.update({
  id: '/api/public/remote-config',
  path: '/api/public/remote-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revendedores': typeof RevendedoresRoute
  '/api/public/remote-config': typeof ApiPublicRemoteConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revendedores': typeof RevendedoresRoute
  '/api/public/remote-config': typeof ApiPublicRemoteConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revendedores': typeof RevendedoresRoute
  '/api/public/remote-config': typeof ApiPublicRemoteConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/revendedores' | '/api/public/remote-config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/revendedores' | '/api/public/remote-config'
  id: '__root__' | '/' | '/revendedores' | '/api/public/remote-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevendedoresRoute: typeof RevendedoresRoute
  ApiPublicRemoteConfigRoute: typeof ApiPublicRemoteConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revendedores': {
      id: '/revendedores'
      path: '/revendedores'
      fullPath: '/revendedores'
      preLoaderRoute: typeof RevendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote-config': {
      id: '/api/public/remote-config'
      path: '/api/public/remote-config'
      fullPath: '/api/public/remote-config'
      preLoaderRoute: typeof ApiPublicRemoteConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevendedoresRoute: RevendedoresRoute,
  ApiPublicRemoteConfigRoute: ApiPublicRemoteConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
